spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authserver
    username: root
    password: yunaxiaozhou1
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      maximum-pool-size: 100
      minimum-idle: 20

  cloud:
    consul:
      host: localhost
      discovery:
        health-check-path: ${server.servlet.context-path:}/actuator/health