server:
  servlet:
    context-path: /auth
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authserver
    username: root
    password: yunaxiaozhou1
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: info