spring:
  cloud:
    consul:
      host: localhost

security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8080/auth/oauth/token
      userAuthorizationUri: http://localhost:8080/auth/oauth/authorize
      clientId: gateway1
      clientSecret: secret
      authorized-grant-types: authorization_code
    resource:
      #userInfoUri: http://localhost:8080/auth/user
      jwt:
        key-uri: http://localhost:8080/auth/oauth/token_key
      prefer-token-info: false
