security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8080/auth/oauth/token
      userAuthorizationUri: http://localhost:8080/auth/oauth/authorize
      clientId: client2
      clientSecret: secret
      authorized-grant-types: authorization_code
    resource:
      userInfoUri: http://localhost:8080/auth/user