spring:
  application:
    name: service1

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    config:
      uri: http://localhost:8888
      profile: dev

server:
  port: 10002


management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  hystrix:
    enabled: true
