spring:
  application:
    name: service1

  cloud:
    consul:
      host: localhost

    config:
      uri: http://localhost:8888
      profile: dev
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
    web:
      client:
        enabled: true

server:
  port: 10002

ribbon:
  ReadTimeout: 20000
  SocketTimeout: 20000


management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  hystrix:
    enabled: true


security:
  oauth2:
    client:
      client-id: service1
      client-secret: secret
      #access-token-uri: http://localhost:8080/auth/oauth/token
      #user-authorization-uri: http://localhost:8080/auth/oauth/authorize
      #grant-type: authorization_code
      #scope: all
    resource:
      jwt:
        key-uri: http://localhost:8080/auth/oauth/token_key
      #token-info-uri: http://localhost:8080/auth/oauth/check_token

#这里很重要，feign就是通过这里获取到token然后传递给下游，折腾我好久。。。
hystrix:
  shareSecurityContext: true

