spring:
  application:
    name: service4

  cloud:
    consul:
      host: localhost

  profiles:
    active: dev
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
    web:
      client:
        enabled: true

server:
  port: 10005

management:
  endpoints:
    web:
      exposure:
        include: "*"
